"""update documents table

Revision ID: dc16c4d88d73
Revises: 
Create Date: 2026-08-18 16:40:47.158408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc16c4d88d73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
